### ISSUE TITLE
The game doesn't even want to start

### ISSUE THREAD

**Issue by deany1014** [AmyMialeeCommissions/annoyingdifficulty#24]
Uncaught exception in thread "main"
java.lang.RuntimeException: error remapping game jars [C:\Users\deane\AppData\Roaming\com.modrinth.theseus\meta\versions\1.20.1-0.14.23\1.20.1-0.14.23.jar]
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:240)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:319)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.NoSuchFileException: C:\Users\deane\AppData\Roaming\com.modrinth.theseus\profiles\FUND!!!!!!!!!!!!!!!\.fabric\remappedJars\minecraft-1.20.1-0.14.23\client-intermediary.jar.tmp
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:342)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:238)
	... 4 more

**Comment by AmyMialee** [comment]
uh try installing with a name without any special characters like !
